export const STORE_ACTIONS = {
  NAVIGATE: "NAVIGATE",
  HUMAN_MOVE: "HUMAN_MOVE",
  COMPUTER_MOVE: "COMPUTER_MOVE",
  UNDO_LAST_MOVE: "UNDO_LAST_MOVE",
  RESTART: "RESTART",
  SET_FIRST_TO_MOVE: "SET_FIRST_TO_MOVE",
  SET_PLAYER_SYMBOL: "SET_PLAYER_SYMBOL",
};
